{
    "targets": [
        {
            "target_name": "node-av",
            "sources": [
                "src/bindings/index.cc",
                "src/bindings/packet.cc",
                "src/bindings/frame.cc",
                "src/bindings/frame_async.cc",
                "src/bindings/frame_sync.cc",
                "src/bindings/codec.cc",
                "src/bindings/codec_context.cc",
                "src/bindings/codec_context_async.cc",
                "src/bindings/codec_context_sync.cc",
                "src/bindings/codec_parameters.cc",
                "src/bindings/codec_parser.cc",
                "src/bindings/format_context.cc",
                "src/bindings/format_context_async.cc",
                "src/bindings/format_context_sync.cc",
                "src/bindings/stream.cc",
                "src/bindings/dictionary.cc",
                "src/bindings/input_format.cc",
                "src/bindings/input_format_async.cc",
                "src/bindings/input_format_sync.cc",
                "src/bindings/output_format.cc",
                "src/bindings/io_context.cc",
                "src/bindings/io_context_async.cc",
                "src/bindings/io_context_sync.cc",
                "src/bindings/error.cc",
                "src/bindings/software_scale_context.cc",
                "src/bindings/software_scale_context_async.cc",
                "src/bindings/software_scale_context_sync.cc",
                "src/bindings/software_resample_context.cc",
                "src/bindings/software_resample_context_async.cc",
                "src/bindings/software_resample_context_sync.cc",
                "src/bindings/filter.cc",
                "src/bindings/filter_context.cc",
                "src/bindings/filter_context_async.cc",
                "src/bindings/filter_context_sync.cc",
                "src/bindings/filter_graph.cc",
                "src/bindings/filter_graph_async.cc",
                "src/bindings/filter_graph_sync.cc",
                "src/bindings/filter_graph_segment.cc",
                "src/bindings/filter_inout.cc",
                "src/bindings/hardware_device_context.cc",
                "src/bindings/hardware_frames_context.cc",
                "src/bindings/hardware_frames_context_async.cc",
                "src/bindings/hardware_frames_context_sync.cc",
                "src/bindings/log.cc",
                "src/bindings/utilities.cc",
                "src/bindings/audio_fifo.cc",
                "src/bindings/audio_fifo_async.cc",
                "src/bindings/audio_fifo_sync.cc",
                "src/bindings/fifo.cc",
                "src/bindings/fifo_async.cc",
                "src/bindings/fifo_sync.cc",
                "src/bindings/frame_utils.cc",
                "src/bindings/scaler.cc",
                "src/bindings/scaler_async.cc",
                "src/bindings/scaler_sync.cc",
                "src/bindings/bitstream_filter.cc",
                "src/bindings/bitstream_filter_context.cc",
                "src/bindings/bitstream_filter_context_async.cc",
                "src/bindings/bitstream_filter_context_sync.cc",
                "src/bindings/option.cc",
                "src/bindings/sync_queue.cc",
                "src/bindings/device.cc",
                "src/bindings/device_sync.cc",
                "src/bindings/device_async.cc",
                "src/bindings/device_win32.cc",
                "src/bindings/gpu_texture_win.cc",
                "externals/jellyfin-ffmpeg/fftools/sync_queue.c",
            ],
            "include_dirs": [
                "<!@(node -p \"require('node-addon-api').include\")",
                "<(module_root_dir)/ffmpeg-msvc/include",
                "<(module_root_dir)/ffmpeg-msvc/include/ffmpeg",
                "<(module_root_dir)/externals/jellyfin-ffmpeg",
                "<(module_root_dir)/externals/jellyfin-ffmpeg/libavcodec",
            ],
            "library_dirs": ["<(module_root_dir)/ffmpeg-msvc/lib"],
            "dependencies": ["<!(node -p \"require('node-addon-api').gyp\")"],
            "cflags!": ["-fno-exceptions"],
            "cflags_cc!": ["-fno-exceptions"],
            "defines": ["NAPI_DISABLE_CPP_EXCEPTIONS"],
            "msvs_settings": {
                "VCCLCompilerTool": {
                    "ExceptionHandling": 1,
                    "RuntimeLibrary": 0,  # /MT
                },
                "VCLinkerTool": {
                    "AdditionalOptions": [
                        "/ignore:4099",
                        "/ignore:4286",
                        "/NODEFAULTLIB:MSVCRT",
                    ],
                    "GenerateDebugInformation": "false",
                    "LinkIncremental": 1,
                    "OptimizeReferences": 2,
                    "EnableCOMDATFolding": 2,
                },
            },
            "libraries": [
                "avformat.lib",
                "avcodec.lib",
                "avfilter.lib",
                "avdevice.lib",
                "avutil.lib",
                "swscale.lib",
                "swresample.lib",
                "libx264.lib",
                "x265-static.lib",
                "vpxmt.lib",
                "opus.lib",
                "mp3lame.lib",
                "fdk-aac.lib",
                "dav1d.lib",
                "SvtAv1Enc.lib",
                "ogg.lib",
                "vorbis.lib",
                "vorbisenc.lib",
                "libwebp.lib",
                "libwebpmux.lib",
                "libwebpdemux.lib",
                "libsharpyuv.lib",
                "libzimg.lib",
                "jxl.lib",
                "jxl_threads.lib",
                "jxl_cms.lib",
                "hwy.lib",
                "ass.lib",
                "harfbuzz.lib",
                "freetype.lib",
                "fribidi.lib",
                "brotlidec.lib",
                "brotlienc.lib",
                "brotlicommon.lib",
                "libxml2.lib",
                "zlib.lib",
                "liblzma.lib",
                "iconv.lib",
                "OpenCL.lib",
                "vulkan-1.lib",
                "libwhisper.lib",
                "libggml.lib",
                "libggml-base.lib",
                "libggml-cpu.lib",
                "libggml-vulkan.lib",
                "libggml-opencl.lib",
                "libomp.lib",
                "shaderc_combined.lib",
                "glslang.lib",
                "MachineIndependent.lib",
                "GenericCodeGen.lib",
                "SPIRV.lib",
                "OSDependent.lib",
                "SPIRV-Tools-opt.lib",
                "SPIRV-Tools.lib",
                "ole32.lib",
                "oleaut32.lib",
                "shlwapi.lib",
                "cfgmgr32.lib",
                "ws2_32.lib",
                "secur32.lib",
                "bcrypt.lib",
                "ncrypt.lib",
                "crypt32.lib",
                "strmiids.lib",
                "mfuuid.lib",
                "psapi.lib",
                "user32.lib",
                "gdi32.lib",
                "advapi32.lib",
                "vfw32.lib",
                "d3d11.lib",
                "dxgi.lib",
            ],
            "conditions": [
                [
                    "target_arch=='x64'",
                    {"libraries": ["vpl.lib"]},
                ],
            ],
        }
    ]
}
