{
    "targets": [
        {
            "target_name": "node-av",
            "sources": [
                "src/bindings/index.cc",
                "src/bindings/packet.cc",
                "src/bindings/frame.cc",
                "src/bindings/frame_async.cc",
                "src/bindings/frame_sync.cc",
                "src/bindings/codec.cc",
                "src/bindings/codec_context.cc",
                "src/bindings/codec_context_async.cc",
                "src/bindings/codec_context_sync.cc",
                "src/bindings/codec_parameters.cc",
                "src/bindings/codec_parser.cc",
                "src/bindings/format_context.cc",
                "src/bindings/format_context_async.cc",
                "src/bindings/format_context_sync.cc",
                "src/bindings/stream.cc",
                "src/bindings/dictionary.cc",
                "src/bindings/input_format.cc",
                "src/bindings/input_format_async.cc",
                "src/bindings/input_format_sync.cc",
                "src/bindings/output_format.cc",
                "src/bindings/io_context.cc",
                "src/bindings/io_context_async.cc",
                "src/bindings/io_context_sync.cc",
                "src/bindings/error.cc",
                "src/bindings/software_scale_context.cc",
                "src/bindings/software_scale_context_async.cc",
                "src/bindings/software_scale_context_sync.cc",
                "src/bindings/software_resample_context.cc",
                "src/bindings/software_resample_context_async.cc",
                "src/bindings/software_resample_context_sync.cc",
                "src/bindings/filter.cc",
                "src/bindings/filter_context.cc",
                "src/bindings/filter_context_async.cc",
                "src/bindings/filter_context_sync.cc",
                "src/bindings/filter_graph.cc",
                "src/bindings/filter_graph_async.cc",
                "src/bindings/filter_graph_sync.cc",
                "src/bindings/filter_graph_segment.cc",
                "src/bindings/filter_inout.cc",
                "src/bindings/hardware_device_context.cc",
                "src/bindings/hardware_frames_context.cc",
                "src/bindings/hardware_frames_context_async.cc",
                "src/bindings/hardware_frames_context_sync.cc",
                "src/bindings/log.cc",
                "src/bindings/utilities.cc",
                "src/bindings/audio_fifo.cc",
                "src/bindings/audio_fifo_async.cc",
                "src/bindings/audio_fifo_sync.cc",
                "src/bindings/fifo.cc",
                "src/bindings/fifo_async.cc",
                "src/bindings/fifo_sync.cc",
                "src/bindings/frame_utils.cc",
                "src/bindings/bitstream_filter.cc",
                "src/bindings/bitstream_filter_context.cc",
                "src/bindings/bitstream_filter_context_async.cc",
                "src/bindings/bitstream_filter_context_sync.cc",
                "src/bindings/option.cc",
                "src/bindings/sync_queue.cc",
                "src/bindings/device.cc",
                "src/bindings/device_sync.cc",
                "src/bindings/device_async.cc",
                "externals/jellyfin-ffmpeg/fftools/sync_queue.c",
            ],
            "include_dirs": [
                "<!@(node -p \"require('node-addon-api').include\")",
                "<(module_root_dir)/externals/jellyfin-ffmpeg",
                "<(module_root_dir)/externals/jellyfin-ffmpeg/libavcodec",
            ],
            "dependencies": ["<!(node -p \"require('node-addon-api').gyp\")"],
            "cflags!": ["-fno-exceptions"],
            "cflags_cc!": ["-fno-exceptions"],
            "defines": ["NAPI_DISABLE_CPP_EXCEPTIONS"],
            "conditions": [
                [
                    "OS=='mac'",
                    {
                        "sources": [
                            "src/bindings/device_darwin.mm",
                        ],
                        "include_dirs": [
                            "/opt/ffbuild/prefix/include",
                        ],
                        "library_dirs": ["/opt/ffbuild/prefix/lib"],
                        "libraries": [
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavformat.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavcodec.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavfilter.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavutil.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswscale.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswresample.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavdevice.a",
                            "-L/opt/ffbuild/prefix/lib",
                            "/opt/ffbuild/prefix/lib/libx264.a",
                            "/opt/ffbuild/prefix/lib/libx265.a",
                            "/opt/ffbuild/prefix/lib/libvpx.a",
                            "/opt/ffbuild/prefix/lib/libopus.a",
                            "/opt/ffbuild/prefix/lib/libmp3lame.a",
                            "/opt/ffbuild/prefix/lib/libdav1d.a",
                            "/opt/ffbuild/prefix/lib/libSvtAv1Enc.a",
                            "/opt/ffbuild/prefix/lib/libogg.a",
                            "/opt/ffbuild/prefix/lib/libvorbis.a",
                            "/opt/ffbuild/prefix/lib/libvorbisenc.a",
                            "/opt/ffbuild/prefix/lib/libtheora.a",
                            "/opt/ffbuild/prefix/lib/libtheoraenc.a",
                            "/opt/ffbuild/prefix/lib/libtheoradec.a",
                            "/opt/ffbuild/prefix/lib/libwebp.a",
                            "/opt/ffbuild/prefix/lib/libwebpmux.a",
                            "/opt/ffbuild/prefix/lib/libsrt.a",
                            "/opt/ffbuild/prefix/lib/libass.a",
                            "/opt/ffbuild/prefix/lib/libharfbuzz.a",
                            "/opt/ffbuild/prefix/lib/libfontconfig.a",
                            "/opt/ffbuild/prefix/lib/libfreetype.a",
                            "/opt/ffbuild/prefix/lib/libfribidi.a",
                            "/opt/ffbuild/prefix/lib/libbluray.a",
                            "/opt/ffbuild/prefix/lib/libudfread.a",
                            "/opt/ffbuild/prefix/lib/libz.a",
                            "/opt/ffbuild/prefix/lib/liblzma.a",
                            "/opt/ffbuild/prefix/lib/libfdk-aac.a",
                            "/opt/ffbuild/prefix/lib/libchromaprint.a",
                            "/opt/ffbuild/prefix/lib/libopenmpt.a",
                            "/opt/ffbuild/prefix/lib/libzvbi.a",
                            "/opt/ffbuild/prefix/lib/libzimg.a",
                            "/opt/ffbuild/prefix/lib/libgmp.a",
                            "/opt/ffbuild/prefix/lib/libssl.a",
                            "/opt/ffbuild/prefix/lib/libcrypto.a",
                            "/opt/ffbuild/prefix/lib/libwhisper.a",
                            "/opt/ffbuild/prefix/lib/libggml.a",
                            "/opt/ffbuild/prefix/lib/libggml-base.a",
                            "/opt/ffbuild/prefix/lib/libggml-cpu.a",
                            "/opt/ffbuild/prefix/lib/libggml-blas.a",
                            "/opt/ffbuild/prefix/lib/libggml-metal.a",
                            "/opt/ffbuild/prefix/lib/libjxl.a",
                            "/opt/ffbuild/prefix/lib/libjxl_threads.a",
                            "/opt/ffbuild/prefix/lib/libjxl_cms.a",
                            "/opt/ffbuild/prefix/lib/libhwy.a",
                            "/opt/ffbuild/prefix/lib/liblcms2.a",
                            "/opt/ffbuild/prefix/lib/libbrotlienc.a",
                            "/opt/ffbuild/prefix/lib/libbrotlidec.a",
                            "/opt/ffbuild/prefix/lib/libbrotlicommon.a",
                            "-liconv",
                            "-lxml2",
                            "-lbz2",
                            "-framework CoreFoundation",
                            "-framework CoreVideo",
                            "-framework CoreMedia",
                            "-framework CoreServices",
                            "-framework AudioToolbox",
                            "-framework VideoToolbox",
                            "-framework AVFoundation",
                            "-framework AppKit",
                            "-framework Accelerate",
                            "-framework Security",
                            "-framework IOKit",
                            "-framework OpenGL",
                            "-framework Metal",
                            "-framework MetalKit",
                            "-framework Foundation",
                            "-framework OpenCL",
                            "-weak_framework ScreenCaptureKit",
                        ],
                        "conditions": [
                            [
                                "target_arch=='arm64'",
                                {
                                    "libraries": [
                                        "/opt/ffbuild/prefix/lib/libNE10.a",
                                    ]
                                },
                            ],
                        ],
                        "xcode_settings": {
                            "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
                            "CLANG_CXX_LIBRARY": "libc++",
                            "CLANG_CXX_LANGUAGE_STANDARD": "c++17",
                            "MACOSX_DEPLOYMENT_TARGET": "12.0",
                            "GCC_SYMBOLS_PRIVATE_EXTERN": "YES",
                            "OTHER_CPLUSPLUSFLAGS": [
                                "-fexceptions",
                                "-fvisibility=hidden",
                                "-fvisibility-inlines-hidden",
                                "-O3",
                            ],
                            "OTHER_LDFLAGS": [
                                "-Wl,-dead_strip",
                                "-Wl,-no_warn_duplicate_libraries",
                                "-Wl,-exported_symbol,_napi_register_module_v1",
                            ],
                            "CONDITIONS": [
                                ["target_arch=='x64'", {"ARCHS": ["x86_64"]}],
                                ["target_arch=='arm64'", {"ARCHS": ["arm64"]}],
                            ],
                        },
                    },
                ],
                [
                    "OS=='linux'",
                    {
                        "sources": [
                            "src/bindings/device_linux.cc",
                        ],
                        "include_dirs": [
                            "/opt/ffbuild/prefix/include",
                        ],
                        "library_dirs": ["/opt/ffbuild/prefix/lib"],
                        "libraries": [
                            "-L/opt/ffbuild/prefix/lib",
                            "-Wl,--whole-archive",
                            "-Wl,--start-group",
                            "/opt/ffbuild/prefix/lib/libavdevice.a",
                            "/opt/ffbuild/prefix/lib/libavfilter.a",
                            "/opt/ffbuild/prefix/lib/libavformat.a",
                            "/opt/ffbuild/prefix/lib/libavcodec.a",
                            "/opt/ffbuild/prefix/lib/libswscale.a",
                            "/opt/ffbuild/prefix/lib/libswresample.a",
                            "/opt/ffbuild/prefix/lib/libavutil.a",
                            "-Wl,--end-group",
                            "-Wl,--no-whole-archive",
                            "/opt/ffbuild/prefix/lib/libx264.a",
                            "/opt/ffbuild/prefix/lib/libx265.a",
                            "/opt/ffbuild/prefix/lib/libvpx.a",
                            "/opt/ffbuild/prefix/lib/libopus.a",
                            "/opt/ffbuild/prefix/lib/libmp3lame.a",
                            "/opt/ffbuild/prefix/lib/libfdk-aac.a",
                            "/opt/ffbuild/prefix/lib/libdav1d.a",
                            "/opt/ffbuild/prefix/lib/libSvtAv1Enc.a",
                            "/opt/ffbuild/prefix/lib/libogg.a",
                            "/opt/ffbuild/prefix/lib/libvorbis.a",
                            "/opt/ffbuild/prefix/lib/libvorbisenc.a",
                            "/opt/ffbuild/prefix/lib/libtheora.a",
                            "/opt/ffbuild/prefix/lib/libtheoraenc.a",
                            "/opt/ffbuild/prefix/lib/libtheoradec.a",
                            "/opt/ffbuild/prefix/lib/libwebp.a",
                            "/opt/ffbuild/prefix/lib/libwebpmux.a",
                            "/opt/ffbuild/prefix/lib/libsharpyuv.a",
                            "/opt/ffbuild/prefix/lib/libsrt.a",
                            "/opt/ffbuild/prefix/lib/libchromaprint.a",
                            "/opt/ffbuild/prefix/lib/libopenmpt.a",
                            "/opt/ffbuild/prefix/lib/libvorbisfile.a",
                            "/opt/ffbuild/prefix/lib/libass.a",
                            "/opt/ffbuild/prefix/lib/libharfbuzz.a",
                            "/opt/ffbuild/prefix/lib/libharfbuzz-subset.a",
                            "/opt/ffbuild/prefix/lib/libfontconfig.a",
                            "/opt/ffbuild/prefix/lib/libfreetype.a",
                            "/opt/ffbuild/prefix/lib/libfribidi.a",
                            "/opt/ffbuild/prefix/lib/libbluray.a",
                            "/opt/ffbuild/prefix/lib/libudfread.a",
                            "/opt/ffbuild/prefix/lib/libjxl.a",
                            "/opt/ffbuild/prefix/lib/libjxl_threads.a",
                            "/opt/ffbuild/prefix/lib/libjxl_cms.a",
                            "/opt/ffbuild/prefix/lib/libhwy.a",
                            "/opt/ffbuild/prefix/lib/liblcms2.a",
                            "/opt/ffbuild/prefix/lib/libbrotlienc.a",
                            "/opt/ffbuild/prefix/lib/libbrotlidec.a",
                            "/opt/ffbuild/prefix/lib/libbrotlicommon.a",
                            "/opt/ffbuild/prefix/lib/libxml2.a",
                            "/opt/ffbuild/prefix/lib/libz.a",
                            "/opt/ffbuild/prefix/lib/liblzma.a",
                            "/opt/ffbuild/prefix/lib/libzvbi.a",
                            "/opt/ffbuild/prefix/lib/libzimg.a",
                            "/opt/ffbuild/prefix/lib/libgmp.a",
                            "/opt/ffbuild/prefix/lib/libssl.a",
                            "/opt/ffbuild/prefix/lib/libcrypto.a",
                            "/opt/ffbuild/prefix/lib/libshaderc_combined.a",
                            "/opt/ffbuild/prefix/lib/libshaderc.a",
                            "/opt/ffbuild/prefix/lib/libshaderc_util.a",
                            "/opt/ffbuild/prefix/lib/libplacebo.a",
                            "/opt/ffbuild/prefix/lib/libglslang.a",
                            "/opt/ffbuild/prefix/lib/libMachineIndependent.a",
                            "/opt/ffbuild/prefix/lib/libGenericCodeGen.a",
                            "/opt/ffbuild/prefix/lib/libSPIRV.a",
                            "/opt/ffbuild/prefix/lib/libOSDependent.a",
                            "/opt/ffbuild/prefix/lib/libglslang-default-resource-limits.a",
                            "/opt/ffbuild/prefix/lib/libSPIRV-Tools.a",
                            "/opt/ffbuild/prefix/lib/libSPIRV-Tools-opt.a",
                            "/opt/ffbuild/prefix/lib/libSPIRV-Tools-link.a",
                            "/opt/ffbuild/prefix/lib/libSPVRemapper.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-core.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-glsl.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-hlsl.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-msl.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-c.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-reflect.a",
                            "/opt/ffbuild/prefix/lib/libspirv-cross-util.a",
                            "/opt/ffbuild/prefix/lib/libOpenCL.a",
                            "/opt/ffbuild/prefix/lib/libvulkan.a",
                            "/opt/ffbuild/prefix/lib/libiconv.a",
                            "/opt/ffbuild/prefix/lib/libfftw3f.a",
                            "/opt/ffbuild/prefix/lib/libcharset.a",
                            "/opt/ffbuild/prefix/lib/liblinebreak.a",
                            "/opt/ffbuild/prefix/lib/libunibreak.a",
                            "/opt/ffbuild/prefix/lib/libwhisper.a",
                            "/opt/ffbuild/prefix/lib/libggml.a",
                            "/opt/ffbuild/prefix/lib/libggml-base.a",
                            "/opt/ffbuild/prefix/lib/libggml-cpu.a",
                            "/opt/ffbuild/prefix/lib/libggml-vulkan.a",
                            "/opt/ffbuild/prefix/lib/libggml-opencl.a",
                            "/opt/ffbuild/prefix/lib/libasound.a",
                            "/opt/ffbuild/prefix/lib/libXv.a",
                            "/opt/ffbuild/prefix/lib/libX11.a",
                            "/opt/ffbuild/prefix/lib/libXext.a",
                            "/opt/ffbuild/prefix/lib/libXfixes.a",
                            "/opt/ffbuild/prefix/lib/libxcb.a",
                            "/opt/ffbuild/prefix/lib/libxcb-shm.a",
                            "/opt/ffbuild/prefix/lib/libxcb-shape.a",
                            "/opt/ffbuild/prefix/lib/libxcb-xfixes.a",
                            "/opt/ffbuild/prefix/lib/libXau.a",
                            "/opt/ffbuild/prefix/lib/libXrandr.a",
                            "/opt/ffbuild/prefix/lib/libXrender.a",
                            "-ldrm",
                            "-lpthread",
                            "-lm",
                            "-ldl",
                            "-lrt",
                            "-latomic",
                            "-lstdc++",
                        ],
                        "cflags": [
                            "-fvisibility=hidden",
                        ],
                        "cflags_cc": [
                            "-std=c++17",
                            "-fexceptions",
                            "-fvisibility=hidden",
                            "-fvisibility-inlines-hidden",
                            "-O3",
                        ],
                        "ldflags": [
                            "-Wl,-Bsymbolic",
                            "-Wl,-rpath,'$$ORIGIN'",
                            "-Wl,--allow-multiple-definition",
                            "-Wl,--exclude-libs,ALL",
                        ],
                        "conditions": [
                            [
                                "target_arch=='x64'",
                                {
                                    "libraries": [
                                        "/opt/ffbuild/prefix/lib/libvpl.a",
                                        "-lva",
                                        "-lva-drm",
                                        "-lva-x11",
                                    ]
                                },
                            ],
                            [
                                "target_arch=='arm64'",
                                {
                                    "libraries": [
                                        "/opt/ffbuild/prefix/lib/librockchip_mpp.a",
                                        "/opt/ffbuild/prefix/lib/librga.a",
                                        "/opt/ffbuild/prefix/lib/libNE10.a",
                                    ]
                                },
                            ],
                        ],
                    },
                ],
                [
                    "OS=='win' or (OS!='mac' and OS!='linux')",  # Mingw
                    {
                        "sources": [
                            "src/bindings/device_win32.cc",
                        ],
                        "conditions": [
                            [
                                "target_arch=='x64'",
                                {
                                    "include_dirs": [
                                        "/clang64/ffbuild/include",
                                    ],
                                    "library_dirs": ["/clang64/ffbuild/lib"],
                                    "libraries": ["-l:libvpl.a"],
                                },
                            ],
                            [
                                "target_arch=='arm64'",
                                {
                                    "include_dirs": [
                                        "/clangarm64/ffbuild/include",
                                    ],
                                    "library_dirs": ["/clangarm64/ffbuild/lib"],
                                },
                            ],
                        ],
                        "libraries": [
                            "-Wl,-Bstatic",
                            "-l:libavformat.a",
                            "-l:libavcodec.a",
                            "-l:libavfilter.a",
                            "-l:libavdevice.a",
                            "-l:libavutil.a",
                            "-l:libswscale.a",
                            "-l:libswresample.a",
                            "-l:libx264.a",
                            "-l:libx265.a",
                            "-l:libvpx.a",
                            "-l:libopus.a",
                            "-l:libmp3lame.a",
                            "-l:libfdk-aac.a",
                            "-l:libdav1d.a",
                            "-l:libSvtAv1Enc.a",
                            "-l:libogg.a",
                            "-l:libvorbis.a",
                            "-l:libvorbisenc.a",
                            "-l:libtheora.a",
                            "-l:libtheoraenc.a",
                            "-l:libtheoradec.a",
                            "-l:libwebp.a",
                            "-l:libwebpmux.a",
                            "-l:libwebpdemux.a",
                            "-l:libsharpyuv.a",
                            "-l:libzimg.a",
                            "-l:libxml2.a",
                            "-l:libfontconfig.a",
                            "-l:libfreetype.a",
                            "-l:libharfbuzz.a",
                            "-l:libharfbuzz-subset.a",
                            "-l:libfribidi.a",
                            "-l:libass.a",
                            "-l:libunibreak.a",
                            "-l:libbluray.a",
                            "-l:libopenmpt.a",
                            "-l:libvorbisfile.a",
                            "-l:libchromaprint.a",
                            "-l:libfftw3f.a",
                            "-l:libpng.a",
                            "-l:libjxl.a",
                            "-l:libjxl_threads.a",
                            "-l:libjxl_cms.a",
                            "-l:libhwy.a",
                            "-l:liblcms2.a",
                            "-l:libbrotlienc.a",
                            "-l:libbrotlidec.a",
                            "-l:libbrotlicommon.a",
                            "-l:libintl.a",
                            "-l:libz.a",
                            "-l:libbz2.a",
                            "-l:liblzma.a",
                            "-l:libiconv.a",
                            "-l:libcharset.a",
                            "-l:libgmp.a",
                            "-l:libhdr10plus.a",
                            "-l:libshaderc_combined.a",
                            "-l:libshaderc.a",
                            "-l:libshaderc_util.a",
                            "-l:libglslang.a",
                            "-l:libMachineIndependent.a",
                            "-l:libGenericCodeGen.a",
                            "-l:libSPIRV.a",
                            "-l:libOSDependent.a",
                            "-l:libglslang-default-resource-limits.a",
                            "-l:libSPIRV-Tools.a",
                            "-l:libSPIRV-Tools-opt.a",
                            "-l:libSPIRV-Tools-link.a",
                            "-l:libSPIRV-Tools-diff.a",
                            "-l:libSPIRV-Tools-reduce.a",
                            "-l:libSPIRV-Tools-lint.a",
                            "-l:libwhisper.a",
                            "-l:libggml.a",
                            "-l:libggml-base.a",
                            "-l:libggml-cpu.a",
                            "-l:libggml-vulkan.a",
                            "-l:libggml-opencl.a",
                            "-l:OpenCL.a",
                            "-l:libvulkan-1.a",
                            "-lomp",
                            "-lpthread",
                            "-Wl,-Bdynamic",
                            "-lole32",
                            "-loleaut32",
                            "-lshlwapi",
                            "-lcfgmgr32",
                            "-lws2_32",
                            "-lsecur32",
                            "-lbcrypt",
                            "-lncrypt",
                            "-lcrypt32",
                            "-lstrmiids",
                            "-lmfuuid",
                            "-lpsapi",
                            "-lvfw32",
                        ],
                        "cflags": [
                            "-fvisibility=hidden",
                        ],
                        "cflags_cc": [
                            "-std=c++17",
                            "-fexceptions",
                            "-fvisibility=hidden",
                            "-fvisibility-inlines-hidden",
                            "-O3",
                        ],
                        "ldflags": [
                            "-static-libgcc",
                            "-static-libstdc++",
                            "-Wl,--gc-sections",
                        ],
                    },
                ],
            ],
        }
    ]
}
