/**
 * Auto-generated FFmpeg decoder constants
 * Generated from FFmpeg source code (allcodecs.c)
 * DO NOT EDIT MANUALLY
 */

import type { CodecContextOptions, DecoderOptionsMap } from './options.js';

// Brand symbols for type safety
declare const __codec_brand: unique symbol;
declare const __codec_name: unique symbol;

// Base decoder type. The optional name parameter carries the codec's literal
// name as a phantom property, enabling codec-specific option typing
// (see DecoderOptionsMap) while the runtime value stays a plain string.
export type FFDecoderCodec<N extends string = string> = string & { readonly [__codec_brand]: 'decoder'; readonly [__codec_name]: N };

// Specific decoder types by media type
export type FFVideoDecoder<N extends string = string> = FFDecoderCodec<N> & { readonly __type: 'video' };
export type FFAudioDecoder<N extends string = string> = FFDecoderCodec<N> & { readonly __type: 'audio' };
export type FFSubtitleDecoder<N extends string = string> = FFDecoderCodec<N> & { readonly __type: 'subtitle' };

/**
 * Loose option bag for codecs without generated option typings
 * (hardware codecs, codecs passed by AVCodecID/Codec, or plain strings).
 */
export type UnknownDecoderOptions = Record<string, string | number | boolean | undefined | null>;

/** Resolve a codec's literal name from its phantom brand, or `never` if unbranded. */
export type DecoderNameOf<C> = C extends FFDecoderCodec<infer N> ? N : never;

/**
 * Resolve the codec-specific private options for a decoder codec.
 *
 * Returns the strongly-typed option set when the codec name is known
 * (enables autocomplete and rejects invalid keys/values), otherwise falls
 * back to {@link UnknownDecoderOptions}.
 */
export type DecoderOptionsFor<C> = [DecoderNameOf<C>] extends [never]
  ? UnknownDecoderOptions
  : DecoderNameOf<C> extends keyof DecoderOptionsMap
    ? Omit<CodecContextOptions, keyof DecoderOptionsMap[DecoderNameOf<C>]> & DecoderOptionsMap[DecoderNameOf<C>]
    : UnknownDecoderOptions;

// ============================================================================
// VIDEO DECODERS (354 software, 49 hardware)
// ============================================================================

// Software video decoders
export const FF_DECODER_AASC = 'aasc' as FFVideoDecoder<'aasc'>;
export const FF_DECODER_ACELP_KELVIN = 'acelp.kelvin' as FFVideoDecoder<'acelp.kelvin'>;
export const FF_DECODER_AGM = 'agm' as FFVideoDecoder<'agm'>;
export const FF_DECODER_AHX = 'ahx' as FFVideoDecoder<'ahx'>;
export const FF_DECODER_AIC = 'aic' as FFVideoDecoder<'aic'>;
export const FF_DECODER_ALIAS_PIX = 'alias_pix' as FFVideoDecoder<'alias_pix'>;
export const FF_DECODER_ALS = 'als' as FFVideoDecoder<'als'>;
export const FF_DECODER_AMV = 'amv' as FFVideoDecoder<'amv'>;
export const FF_DECODER_ANM = 'anm' as FFVideoDecoder<'anm'>;
export const FF_DECODER_ANSI = 'ansi' as FFVideoDecoder<'ansi'>;
export const FF_DECODER_ANULL = 'anull' as FFVideoDecoder<'anull'>;
export const FF_DECODER_APAC = 'apac' as FFVideoDecoder<'apac'>;
export const FF_DECODER_APE = 'ape' as FFVideoDecoder<'ape'>;
export const FF_DECODER_APNG = 'apng' as FFVideoDecoder<'apng'>;
export const FF_DECODER_APV = 'apv' as FFVideoDecoder<'apv'>;
export const FF_DECODER_ARBC = 'arbc' as FFVideoDecoder<'arbc'>;
export const FF_DECODER_ARGO = 'argo' as FFVideoDecoder<'argo'>;
export const FF_DECODER_ASV1 = 'asv1' as FFVideoDecoder<'asv1'>;
export const FF_DECODER_ASV2 = 'asv2' as FFVideoDecoder<'asv2'>;
export const FF_DECODER_AURA = 'aura' as FFVideoDecoder<'aura'>;
export const FF_DECODER_AURA2 = 'aura2' as FFVideoDecoder<'aura2'>;
export const FF_DECODER_AV1 = 'av1' as FFVideoDecoder<'av1'>;
export const FF_DECODER_AV1_AMF = 'av1_amf' as FFVideoDecoder<'av1_amf'>;
export const FF_DECODER_AVRN = 'avrn' as FFVideoDecoder<'avrn'>;
export const FF_DECODER_AVRP = 'avrp' as FFVideoDecoder<'avrp'>;
export const FF_DECODER_AVS = 'avs' as FFVideoDecoder<'avs'>;
export const FF_DECODER_AVUI = 'avui' as FFVideoDecoder<'avui'>;
export const FF_DECODER_BETHSOFTVID = 'bethsoftvid' as FFVideoDecoder<'bethsoftvid'>;
export const FF_DECODER_BFI = 'bfi' as FFVideoDecoder<'bfi'>;
export const FF_DECODER_BINK = 'binkvideo' as FFVideoDecoder<'binkvideo'>;
export const FF_DECODER_BINKAUDIO_DCT = 'binkaudio_dct' as FFVideoDecoder<'binkaudio_dct'>;
export const FF_DECODER_BINKAUDIO_RDFT = 'binkaudio_rdft' as FFVideoDecoder<'binkaudio_rdft'>;
export const FF_DECODER_BINTEXT = 'bintext' as FFVideoDecoder<'bintext'>;
export const FF_DECODER_BITPACKED = 'bitpacked' as FFVideoDecoder<'bitpacked'>;
export const FF_DECODER_BMP = 'bmp' as FFVideoDecoder<'bmp'>;
export const FF_DECODER_BMV_AUDIO = 'bmv_audio' as FFVideoDecoder<'bmv_audio'>;
export const FF_DECODER_BMV_VIDEO = 'bmv_video' as FFVideoDecoder<'bmv_video'>;
export const FF_DECODER_BONK = 'bonk' as FFVideoDecoder<'bonk'>;
export const FF_DECODER_BRENDER_PIX = 'brender_pix' as FFVideoDecoder<'brender_pix'>;
export const FF_DECODER_C93 = 'c93' as FFVideoDecoder<'c93'>;
export const FF_DECODER_CAVS = 'cavs' as FFVideoDecoder<'cavs'>;
export const FF_DECODER_CBD2_DPCM = 'cbd2_dpcm' as FFVideoDecoder<'cbd2_dpcm'>;
export const FF_DECODER_CCAPTION = 'cc_dec' as FFVideoDecoder<'cc_dec'>;
export const FF_DECODER_CDGRAPHICS = 'cdgraphics' as FFVideoDecoder<'cdgraphics'>;
export const FF_DECODER_CDTOONS = 'cdtoons' as FFVideoDecoder<'cdtoons'>;
export const FF_DECODER_CDXL = 'cdxl' as FFVideoDecoder<'cdxl'>;
export const FF_DECODER_CFHD = 'cfhd' as FFVideoDecoder<'cfhd'>;
export const FF_DECODER_CINEPAK = 'cinepak' as FFVideoDecoder<'cinepak'>;
export const FF_DECODER_CLEARVIDEO = 'clearvideo' as FFVideoDecoder<'clearvideo'>;
export const FF_DECODER_CLJR = 'cljr' as FFVideoDecoder<'cljr'>;
export const FF_DECODER_CLLC = 'cllc' as FFVideoDecoder<'cllc'>;
export const FF_DECODER_CPIA = 'cpia' as FFVideoDecoder<'cpia'>;
export const FF_DECODER_CRI = 'cri' as FFVideoDecoder<'cri'>;
export const FF_DECODER_CSCD = 'camstudio' as FFVideoDecoder<'camstudio'>;
export const FF_DECODER_CYUV = 'cyuv' as FFVideoDecoder<'cyuv'>;
export const FF_DECODER_DDS = 'dds' as FFVideoDecoder<'dds'>;
export const FF_DECODER_DERF_DPCM = 'derf_dpcm' as FFVideoDecoder<'derf_dpcm'>;
export const FF_DECODER_DFA = 'dfa' as FFVideoDecoder<'dfa'>;
export const FF_DECODER_DIRAC = 'dirac' as FFVideoDecoder<'dirac'>;
export const FF_DECODER_DNXHD = 'dnxhd' as FFVideoDecoder<'dnxhd'>;
export const FF_DECODER_DPX = 'dpx' as FFVideoDecoder<'dpx'>;
export const FF_DECODER_DSD_LSBF = 'dsd_lsbf' as FFVideoDecoder<'dsd_lsbf'>;
export const FF_DECODER_DSD_LSBF_PLANAR = 'dsd_lsbf_planar' as FFVideoDecoder<'dsd_lsbf_planar'>;
export const FF_DECODER_DSD_MSBF = 'dsd_msbf' as FFVideoDecoder<'dsd_msbf'>;
export const FF_DECODER_DSD_MSBF_PLANAR = 'dsd_msbf_planar' as FFVideoDecoder<'dsd_msbf_planar'>;
export const FF_DECODER_DSICINAUDIO = 'dsicinaudio' as FFVideoDecoder<'dsicinaudio'>;
export const FF_DECODER_DSICINVIDEO = 'dsicinvideo' as FFVideoDecoder<'dsicinvideo'>;
export const FF_DECODER_DSS_SP = 'dss_sp' as FFVideoDecoder<'dss_sp'>;
export const FF_DECODER_DST = 'dst' as FFVideoDecoder<'dst'>;
export const FF_DECODER_DVAUDIO = 'dvaudio' as FFVideoDecoder<'dvaudio'>;
export const FF_DECODER_DVVIDEO = 'dvvideo' as FFVideoDecoder<'dvvideo'>;
export const FF_DECODER_DXA = 'dxa' as FFVideoDecoder<'dxa'>;
export const FF_DECODER_DXTORY = 'dxtory' as FFVideoDecoder<'dxtory'>;
export const FF_DECODER_DXV = 'dxv' as FFVideoDecoder<'dxv'>;
export const FF_DECODER_EACMV = 'eacmv' as FFVideoDecoder<'eacmv'>;
export const FF_DECODER_EAMAD = 'eamad' as FFVideoDecoder<'eamad'>;
export const FF_DECODER_EATGQ = 'eatgq' as FFVideoDecoder<'eatgq'>;
export const FF_DECODER_EATGV = 'eatgv' as FFVideoDecoder<'eatgv'>;
export const FF_DECODER_EATQI = 'eatqi' as FFVideoDecoder<'eatqi'>;
export const FF_DECODER_EIGHTBPS = '8bps' as FFVideoDecoder<'8bps'>;
export const FF_DECODER_EIGHTSVX_EXP = '8svx_exp' as FFVideoDecoder<'8svx_exp'>;
export const FF_DECODER_EIGHTSVX_FIB = '8svx_fib' as FFVideoDecoder<'8svx_fib'>;
export const FF_DECODER_ESCAPE124 = 'escape124' as FFVideoDecoder<'escape124'>;
export const FF_DECODER_ESCAPE130 = 'escape130' as FFVideoDecoder<'escape130'>;
export const FF_DECODER_EVRC = 'evrc' as FFVideoDecoder<'evrc'>;
export const FF_DECODER_EXR = 'exr' as FFVideoDecoder<'exr'>;
export const FF_DECODER_FASTAUDIO = 'fastaudio' as FFVideoDecoder<'fastaudio'>;
export const FF_DECODER_FFV1 = 'ffv1' as FFVideoDecoder<'ffv1'>;
export const FF_DECODER_FFVHUFF = 'ffvhuff' as FFVideoDecoder<'ffvhuff'>;
export const FF_DECODER_FFWAVESYNTH = 'wavesynth' as FFVideoDecoder<'wavesynth'>;
export const FF_DECODER_FIC = 'fic' as FFVideoDecoder<'fic'>;
export const FF_DECODER_FITS = 'fits' as FFVideoDecoder<'fits'>;
export const FF_DECODER_FLASHSV = 'flashsv' as FFVideoDecoder<'flashsv'>;
export const FF_DECODER_FLASHSV2 = 'flashsv2' as FFVideoDecoder<'flashsv2'>;
export const FF_DECODER_FLIC = 'flic' as FFVideoDecoder<'flic'>;
export const FF_DECODER_FLV = 'flv' as FFVideoDecoder<'flv'>;
export const FF_DECODER_FMVC = 'fmvc' as FFVideoDecoder<'fmvc'>;
export const FF_DECODER_FOURXM = '4xm' as FFVideoDecoder<'4xm'>;
export const FF_DECODER_FRAPS = 'fraps' as FFVideoDecoder<'fraps'>;
export const FF_DECODER_FRWU = 'frwu' as FFVideoDecoder<'frwu'>;
export const FF_DECODER_FTR = 'ftr' as FFVideoDecoder<'ftr'>;
export const FF_DECODER_G2M = 'g2m' as FFVideoDecoder<'g2m'>;
export const FF_DECODER_GDV = 'gdv' as FFVideoDecoder<'gdv'>;
export const FF_DECODER_GEM = 'gem' as FFVideoDecoder<'gem'>;
export const FF_DECODER_GIF = 'gif' as FFVideoDecoder<'gif'>;
export const FF_DECODER_GREMLIN_DPCM = 'gremlin_dpcm' as FFVideoDecoder<'gremlin_dpcm'>;
export const FF_DECODER_H261 = 'h261' as FFVideoDecoder<'h261'>;
export const FF_DECODER_H263 = 'h263' as FFVideoDecoder<'h263'>;
export const FF_DECODER_H263I = 'h263i' as FFVideoDecoder<'h263i'>;
export const FF_DECODER_H263P = 'h263p' as FFVideoDecoder<'h263p'>;
export const FF_DECODER_H264 = 'h264' as FFVideoDecoder<'h264'>;
export const FF_DECODER_H264_AMF = 'h264_amf' as FFVideoDecoder<'h264_amf'>;
export const FF_DECODER_H264_OH = 'h264_oh' as FFVideoDecoder<'h264_oh'>;
export const FF_DECODER_HAP = 'hap' as FFVideoDecoder<'hap'>;
export const FF_DECODER_HCA = 'hca' as FFVideoDecoder<'hca'>;
export const FF_DECODER_HCOM = 'hcom' as FFVideoDecoder<'hcom'>;
export const FF_DECODER_HDR = 'hdr' as FFVideoDecoder<'hdr'>;
export const FF_DECODER_HEVC = 'hevc' as FFVideoDecoder<'hevc'>;
export const FF_DECODER_HEVC_AMF = 'hevc_amf' as FFVideoDecoder<'hevc_amf'>;
export const FF_DECODER_HEVC_OH = 'hevc_oh' as FFVideoDecoder<'hevc_oh'>;
export const FF_DECODER_HNM4_VIDEO = 'hnm4video' as FFVideoDecoder<'hnm4video'>;
export const FF_DECODER_HQ_HQA = 'hq_hqa' as FFVideoDecoder<'hq_hqa'>;
export const FF_DECODER_HQX = 'hqx' as FFVideoDecoder<'hqx'>;
export const FF_DECODER_HUFFYUV = 'huffyuv' as FFVideoDecoder<'huffyuv'>;
export const FF_DECODER_HYMT = 'hymt' as FFVideoDecoder<'hymt'>;
export const FF_DECODER_IAC = 'iac' as FFVideoDecoder<'iac'>;
export const FF_DECODER_IDCIN = 'idcinvideo' as FFVideoDecoder<'idcinvideo'>;
export const FF_DECODER_IDF = 'idf' as FFVideoDecoder<'idf'>;
export const FF_DECODER_IFF_ILBM = 'iff' as FFVideoDecoder<'iff'>;
export const FF_DECODER_IMM4 = 'imm4' as FFVideoDecoder<'imm4'>;
export const FF_DECODER_IMM5 = 'imm5' as FFVideoDecoder<'imm5'>;
export const FF_DECODER_INDEO2 = 'indeo2' as FFVideoDecoder<'indeo2'>;
export const FF_DECODER_INDEO3 = 'indeo3' as FFVideoDecoder<'indeo3'>;
export const FF_DECODER_INDEO4 = 'indeo4' as FFVideoDecoder<'indeo4'>;
export const FF_DECODER_INDEO5 = 'indeo5' as FFVideoDecoder<'indeo5'>;
export const FF_DECODER_INTERPLAY_ACM = 'interplayacm' as FFVideoDecoder<'interplayacm'>;
export const FF_DECODER_INTERPLAY_DPCM = 'interplay_dpcm' as FFVideoDecoder<'interplay_dpcm'>;
export const FF_DECODER_INTERPLAY_VIDEO = 'interplayvideo' as FFVideoDecoder<'interplayvideo'>;
export const FF_DECODER_IPU = 'ipu' as FFVideoDecoder<'ipu'>;
export const FF_DECODER_JPEG2000 = 'jpeg2000' as FFVideoDecoder<'jpeg2000'>;
export const FF_DECODER_JPEGLS = 'jpegls' as FFVideoDecoder<'jpegls'>;
export const FF_DECODER_JV = 'jv' as FFVideoDecoder<'jv'>;
export const FF_DECODER_KGV1 = 'kgv1' as FFVideoDecoder<'kgv1'>;
export const FF_DECODER_KMVC = 'kmvc' as FFVideoDecoder<'kmvc'>;
export const FF_DECODER_LAGARITH = 'lagarith' as FFVideoDecoder<'lagarith'>;
export const FF_DECODER_LEAD = 'lead' as FFVideoDecoder<'lead'>;
export const FF_DECODER_LIBAOM_AV1 = 'libaom-av1' as FFVideoDecoder<'libaom-av1'>;
export const FF_DECODER_LIBARIBB24 = 'libaribb24' as FFVideoDecoder<'libaribb24'>;
export const FF_DECODER_LIBARIBCAPTION = 'libaribcaption' as FFVideoDecoder<'libaribcaption'>;
export const FF_DECODER_LIBCODEC2 = 'libcodec2' as FFVideoDecoder<'libcodec2'>;
export const FF_DECODER_LIBDAV1D = 'libdav1d' as FFVideoDecoder<'libdav1d'>;
export const FF_DECODER_LIBDAVS2 = 'libdavs2' as FFVideoDecoder<'libdavs2'>;
export const FF_DECODER_LIBGSM = 'libgsm' as FFVideoDecoder<'libgsm'>;
export const FF_DECODER_LIBGSM_MS = 'libgsm_ms' as FFVideoDecoder<'libgsm_ms'>;
export const FF_DECODER_LIBILBC = 'libilbc' as FFVideoDecoder<'libilbc'>;
export const FF_DECODER_LIBJXL = 'libjxl' as FFVideoDecoder<'libjxl'>;
export const FF_DECODER_LIBJXL_ANIM = 'libjxl_anim' as FFVideoDecoder<'libjxl_anim'>;
export const FF_DECODER_LIBLC3 = 'liblc3' as FFVideoDecoder<'liblc3'>;
export const FF_DECODER_LIBMPEGHDEC = 'libmpeghdec' as FFVideoDecoder<'libmpeghdec'>;
export const FF_DECODER_LIBOPENCORE_AMRNB = 'libopencore_amrnb' as FFVideoDecoder<'libopencore_amrnb'>;
export const FF_DECODER_LIBOPENCORE_AMRWB = 'libopencore_amrwb' as FFVideoDecoder<'libopencore_amrwb'>;
export const FF_DECODER_LIBOPENH264 = 'libopenh264' as FFVideoDecoder<'libopenh264'>;
export const FF_DECODER_LIBRSVG = 'librsvg' as FFVideoDecoder<'librsvg'>;
export const FF_DECODER_LIBSVTJPEGXS = 'libsvtjpegxs' as FFVideoDecoder<'libsvtjpegxs'>;
export const FF_DECODER_LIBUAVS3D = 'libuavs3d' as FFVideoDecoder<'libuavs3d'>;
export const FF_DECODER_LIBVPX_VP8 = 'libvpx' as FFVideoDecoder<'libvpx'>;
export const FF_DECODER_LIBVPX_VP9 = 'libvpx-vp9' as FFVideoDecoder<'libvpx-vp9'>;
export const FF_DECODER_LIBXEVD = 'evc' as FFVideoDecoder<'evc'>;
export const FF_DECODER_LIBZVBI_TELETEXT = 'libzvbi_teletextdec' as FFVideoDecoder<'libzvbi_teletextdec'>;
export const FF_DECODER_LOCO = 'loco' as FFVideoDecoder<'loco'>;
export const FF_DECODER_LSCR = 'lscr' as FFVideoDecoder<'lscr'>;
export const FF_DECODER_M101 = 'm101' as FFVideoDecoder<'m101'>;
export const FF_DECODER_MAGICYUV = 'magicyuv' as FFVideoDecoder<'magicyuv'>;
export const FF_DECODER_MDEC = 'mdec' as FFVideoDecoder<'mdec'>;
export const FF_DECODER_MEDIA100 = 'media100' as FFVideoDecoder<'media100'>;
export const FF_DECODER_MIMIC = 'mimic' as FFVideoDecoder<'mimic'>;
export const FF_DECODER_MISC4 = 'misc4' as FFVideoDecoder<'misc4'>;
export const FF_DECODER_MJPEG = 'mjpeg' as FFVideoDecoder<'mjpeg'>;
export const FF_DECODER_MJPEGB = 'mjpegb' as FFVideoDecoder<'mjpegb'>;
export const FF_DECODER_MMVIDEO = 'mmvideo' as FFVideoDecoder<'mmvideo'>;
export const FF_DECODER_MOBICLIP = 'mobiclip' as FFVideoDecoder<'mobiclip'>;
export const FF_DECODER_MOTIONPIXELS = 'motionpixels' as FFVideoDecoder<'motionpixels'>;
export const FF_DECODER_MOVTEXT = 'mov_text' as FFVideoDecoder<'mov_text'>;
export const FF_DECODER_MPC7 = 'mpc7' as FFVideoDecoder<'mpc7'>;
export const FF_DECODER_MPC8 = 'mpc8' as FFVideoDecoder<'mpc8'>;
export const FF_DECODER_MPEG1VIDEO = 'mpeg1video' as FFVideoDecoder<'mpeg1video'>;
export const FF_DECODER_MPEG2VIDEO = 'mpeg2video' as FFVideoDecoder<'mpeg2video'>;
export const FF_DECODER_MPEG4 = 'mpeg4' as FFVideoDecoder<'mpeg4'>;
export const FF_DECODER_MPEGVIDEO = 'mpegvideo' as FFVideoDecoder<'mpegvideo'>;
export const FF_DECODER_MSA1 = 'msa1' as FFVideoDecoder<'msa1'>;
export const FF_DECODER_MSCC = 'mscc' as FFVideoDecoder<'mscc'>;
export const FF_DECODER_MSMPEG4V1 = 'msmpeg4v1' as FFVideoDecoder<'msmpeg4v1'>;
export const FF_DECODER_MSMPEG4V2 = 'msmpeg4v2' as FFVideoDecoder<'msmpeg4v2'>;
export const FF_DECODER_MSMPEG4V3 = 'msmpeg4' as FFVideoDecoder<'msmpeg4'>;
export const FF_DECODER_MSNSIREN = 'msnsiren' as FFVideoDecoder<'msnsiren'>;
export const FF_DECODER_MSP2 = 'msp2' as FFVideoDecoder<'msp2'>;
export const FF_DECODER_MSRLE = 'msrle' as FFVideoDecoder<'msrle'>;
export const FF_DECODER_MSS1 = 'mss1' as FFVideoDecoder<'mss1'>;
export const FF_DECODER_MSS2 = 'mss2' as FFVideoDecoder<'mss2'>;
export const FF_DECODER_MSVIDEO1 = 'msvideo1' as FFVideoDecoder<'msvideo1'>;
export const FF_DECODER_MSZH = 'mszh' as FFVideoDecoder<'mszh'>;
export const FF_DECODER_MTS2 = 'mts2' as FFVideoDecoder<'mts2'>;
export const FF_DECODER_MV30 = 'mv30' as FFVideoDecoder<'mv30'>;
export const FF_DECODER_MVC1 = 'mvc1' as FFVideoDecoder<'mvc1'>;
export const FF_DECODER_MVC2 = 'mvc2' as FFVideoDecoder<'mvc2'>;
export const FF_DECODER_MVDV = 'mvdv' as FFVideoDecoder<'mvdv'>;
export const FF_DECODER_MVHA = 'mvha' as FFVideoDecoder<'mvha'>;
export const FF_DECODER_MWSC = 'mwsc' as FFVideoDecoder<'mwsc'>;
export const FF_DECODER_MXPEG = 'mxpeg' as FFVideoDecoder<'mxpeg'>;
export const FF_DECODER_NOTCHLC = 'notchlc' as FFVideoDecoder<'notchlc'>;
export const FF_DECODER_NUV = 'nuv' as FFVideoDecoder<'nuv'>;
export const FF_DECODER_OSQ = 'osq' as FFVideoDecoder<'osq'>;
export const FF_DECODER_PAF_AUDIO = 'paf_audio' as FFVideoDecoder<'paf_audio'>;
export const FF_DECODER_PAF_VIDEO = 'paf_video' as FFVideoDecoder<'paf_video'>;
export const FF_DECODER_PAM = 'pam' as FFVideoDecoder<'pam'>;
export const FF_DECODER_PBM = 'pbm' as FFVideoDecoder<'pbm'>;
export const FF_DECODER_PCX = 'pcx' as FFVideoDecoder<'pcx'>;
export const FF_DECODER_PDV = 'pdv' as FFVideoDecoder<'pdv'>;
export const FF_DECODER_PFM = 'pfm' as FFVideoDecoder<'pfm'>;
export const FF_DECODER_PGM = 'pgm' as FFVideoDecoder<'pgm'>;
export const FF_DECODER_PGMYUV = 'pgmyuv' as FFVideoDecoder<'pgmyuv'>;
export const FF_DECODER_PGSSUB = 'pgssub' as FFVideoDecoder<'pgssub'>;
export const FF_DECODER_PGX = 'pgx' as FFVideoDecoder<'pgx'>;
export const FF_DECODER_PHM = 'phm' as FFVideoDecoder<'phm'>;
export const FF_DECODER_PHOTOCD = 'photocd' as FFVideoDecoder<'photocd'>;
export const FF_DECODER_PICTOR = 'pictor' as FFVideoDecoder<'pictor'>;
export const FF_DECODER_PIXLET = 'pixlet' as FFVideoDecoder<'pixlet'>;
export const FF_DECODER_PNG = 'png' as FFVideoDecoder<'png'>;
export const FF_DECODER_PPM = 'ppm' as FFVideoDecoder<'ppm'>;
export const FF_DECODER_PRORES = 'prores' as FFVideoDecoder<'prores'>;
export const FF_DECODER_PRORES_RAW = 'prores_raw' as FFVideoDecoder<'prores_raw'>;
export const FF_DECODER_PROSUMER = 'prosumer' as FFVideoDecoder<'prosumer'>;
export const FF_DECODER_PSD = 'psd' as FFVideoDecoder<'psd'>;
export const FF_DECODER_PTX = 'ptx' as FFVideoDecoder<'ptx'>;
export const FF_DECODER_QDRAW = 'qdraw' as FFVideoDecoder<'qdraw'>;
export const FF_DECODER_QOA = 'qoa' as FFVideoDecoder<'qoa'>;
export const FF_DECODER_QOI = 'qoi' as FFVideoDecoder<'qoi'>;
export const FF_DECODER_QPEG = 'qpeg' as FFVideoDecoder<'qpeg'>;
export const FF_DECODER_QTRLE = 'qtrle' as FFVideoDecoder<'qtrle'>;
export const FF_DECODER_R10K = 'r10k' as FFVideoDecoder<'r10k'>;
export const FF_DECODER_R210 = 'r210' as FFVideoDecoder<'r210'>;
export const FF_DECODER_RA_144 = 'real_144' as FFVideoDecoder<'real_144'>;
export const FF_DECODER_RA_288 = 'real_288' as FFVideoDecoder<'real_288'>;
export const FF_DECODER_RASC = 'rasc' as FFVideoDecoder<'rasc'>;
export const FF_DECODER_RAWVIDEO = 'rawvideo' as FFVideoDecoder<'rawvideo'>;
export const FF_DECODER_RKA = 'rka' as FFVideoDecoder<'rka'>;
export const FF_DECODER_RL2 = 'rl2' as FFVideoDecoder<'rl2'>;
export const FF_DECODER_ROQ = 'roqvideo' as FFVideoDecoder<'roqvideo'>;
export const FF_DECODER_ROQ_DPCM = 'roq_dpcm' as FFVideoDecoder<'roq_dpcm'>;
export const FF_DECODER_RPZA = 'rpza' as FFVideoDecoder<'rpza'>;
export const FF_DECODER_RSCC = 'rscc' as FFVideoDecoder<'rscc'>;
export const FF_DECODER_RTV1 = 'rtv1' as FFVideoDecoder<'rtv1'>;
export const FF_DECODER_RV10 = 'rv10' as FFVideoDecoder<'rv10'>;
export const FF_DECODER_RV20 = 'rv20' as FFVideoDecoder<'rv20'>;
export const FF_DECODER_RV30 = 'rv30' as FFVideoDecoder<'rv30'>;
export const FF_DECODER_RV40 = 'rv40' as FFVideoDecoder<'rv40'>;
export const FF_DECODER_RV60 = 'rv60' as FFVideoDecoder<'rv60'>;
export const FF_DECODER_SANM = 'sanm' as FFVideoDecoder<'sanm'>;
export const FF_DECODER_SCPR = 'scpr' as FFVideoDecoder<'scpr'>;
export const FF_DECODER_SCREENPRESSO = 'screenpresso' as FFVideoDecoder<'screenpresso'>;
export const FF_DECODER_SDX2_DPCM = 'sdx2_dpcm' as FFVideoDecoder<'sdx2_dpcm'>;
export const FF_DECODER_SGA = 'sga' as FFVideoDecoder<'sga'>;
export const FF_DECODER_SGI = 'sgi' as FFVideoDecoder<'sgi'>;
export const FF_DECODER_SGIRLE = 'sgirle' as FFVideoDecoder<'sgirle'>;
export const FF_DECODER_SHEERVIDEO = 'sheervideo' as FFVideoDecoder<'sheervideo'>;
export const FF_DECODER_SHORTEN = 'shorten' as FFVideoDecoder<'shorten'>;
export const FF_DECODER_SIMBIOSIS_IMX = 'simbiosis_imx' as FFVideoDecoder<'simbiosis_imx'>;
export const FF_DECODER_SIREN = 'siren' as FFVideoDecoder<'siren'>;
export const FF_DECODER_SMACKAUD = 'smackaud' as FFVideoDecoder<'smackaud'>;
export const FF_DECODER_SMACKER = 'smackvid' as FFVideoDecoder<'smackvid'>;
export const FF_DECODER_SMC = 'smc' as FFVideoDecoder<'smc'>;
export const FF_DECODER_SMVJPEG = 'smvjpeg' as FFVideoDecoder<'smvjpeg'>;
export const FF_DECODER_SNOW = 'snow' as FFVideoDecoder<'snow'>;
export const FF_DECODER_SOL_DPCM = 'sol_dpcm' as FFVideoDecoder<'sol_dpcm'>;
export const FF_DECODER_SP5X = 'sp5x' as FFVideoDecoder<'sp5x'>;
export const FF_DECODER_SPEEDHQ = 'speedhq' as FFVideoDecoder<'speedhq'>;
export const FF_DECODER_SPEEX = 'speex' as FFVideoDecoder<'speex'>;
export const FF_DECODER_SRGC = 'srgc' as FFVideoDecoder<'srgc'>;
export const FF_DECODER_SUNRAST = 'sunrast' as FFVideoDecoder<'sunrast'>;
export const FF_DECODER_SVQ1 = 'svq1' as FFVideoDecoder<'svq1'>;
export const FF_DECODER_SVQ3 = 'svq3' as FFVideoDecoder<'svq3'>;
export const FF_DECODER_TARGA = 'targa' as FFVideoDecoder<'targa'>;
export const FF_DECODER_TARGA_Y216 = 'targa_y216' as FFVideoDecoder<'targa_y216'>;
export const FF_DECODER_TDSC = 'tdsc' as FFVideoDecoder<'tdsc'>;
export const FF_DECODER_THEORA = 'theora' as FFVideoDecoder<'theora'>;
export const FF_DECODER_THP = 'thp' as FFVideoDecoder<'thp'>;
export const FF_DECODER_TIERTEXSEQVIDEO = 'tiertexseqvideo' as FFVideoDecoder<'tiertexseqvideo'>;
export const FF_DECODER_TIFF = 'tiff' as FFVideoDecoder<'tiff'>;
export const FF_DECODER_TMV = 'tmv' as FFVideoDecoder<'tmv'>;
export const FF_DECODER_TRUEMOTION1 = 'truemotion1' as FFVideoDecoder<'truemotion1'>;
export const FF_DECODER_TRUEMOTION2 = 'truemotion2' as FFVideoDecoder<'truemotion2'>;
export const FF_DECODER_TRUEMOTION2RT = 'truemotion2rt' as FFVideoDecoder<'truemotion2rt'>;
export const FF_DECODER_TSCC = 'camtasia' as FFVideoDecoder<'camtasia'>;
export const FF_DECODER_TSCC2 = 'tscc2' as FFVideoDecoder<'tscc2'>;
export const FF_DECODER_TXD = 'txd' as FFVideoDecoder<'txd'>;
export const FF_DECODER_ULTI = 'ultimotion' as FFVideoDecoder<'ultimotion'>;
export const FF_DECODER_UTVIDEO = 'utvideo' as FFVideoDecoder<'utvideo'>;
export const FF_DECODER_V210 = 'v210' as FFVideoDecoder<'v210'>;
export const FF_DECODER_V210X = 'v210x' as FFVideoDecoder<'v210x'>;
export const FF_DECODER_V308 = 'v308' as FFVideoDecoder<'v308'>;
export const FF_DECODER_V408 = 'v408' as FFVideoDecoder<'v408'>;
export const FF_DECODER_V410 = 'v410' as FFVideoDecoder<'v410'>;
export const FF_DECODER_VB = 'vb' as FFVideoDecoder<'vb'>;
export const FF_DECODER_VBLE = 'vble' as FFVideoDecoder<'vble'>;
export const FF_DECODER_VBN = 'vbn' as FFVideoDecoder<'vbn'>;
export const FF_DECODER_VC1 = 'vc1' as FFVideoDecoder<'vc1'>;
export const FF_DECODER_VC1IMAGE = 'vc1image' as FFVideoDecoder<'vc1image'>;
export const FF_DECODER_VCR1 = 'vcr1' as FFVideoDecoder<'vcr1'>;
export const FF_DECODER_VMDVIDEO = 'vmdvideo' as FFVideoDecoder<'vmdvideo'>;
export const FF_DECODER_VMIX = 'vmix' as FFVideoDecoder<'vmix'>;
export const FF_DECODER_VMNC = 'vmnc' as FFVideoDecoder<'vmnc'>;
export const FF_DECODER_VNULL = 'vnull' as FFVideoDecoder<'vnull'>;
export const FF_DECODER_VP3 = 'vp3' as FFVideoDecoder<'vp3'>;
export const FF_DECODER_VP4 = 'vp4' as FFVideoDecoder<'vp4'>;
export const FF_DECODER_VP5 = 'vp5' as FFVideoDecoder<'vp5'>;
export const FF_DECODER_VP6 = 'vp6' as FFVideoDecoder<'vp6'>;
export const FF_DECODER_VP6A = 'vp6a' as FFVideoDecoder<'vp6a'>;
export const FF_DECODER_VP6F = 'vp6f' as FFVideoDecoder<'vp6f'>;
export const FF_DECODER_VP7 = 'vp7' as FFVideoDecoder<'vp7'>;
export const FF_DECODER_VP8 = 'vp8' as FFVideoDecoder<'vp8'>;
export const FF_DECODER_VP9 = 'vp9' as FFVideoDecoder<'vp9'>;
export const FF_DECODER_VP9_AMF = 'vp9_amf' as FFVideoDecoder<'vp9_amf'>;
export const FF_DECODER_VQA = 'vqavideo' as FFVideoDecoder<'vqavideo'>;
export const FF_DECODER_VQC = 'vqc' as FFVideoDecoder<'vqc'>;
export const FF_DECODER_VVC = 'vvc' as FFVideoDecoder<'vvc'>;
export const FF_DECODER_WADY_DPCM = 'wady_dpcm' as FFVideoDecoder<'wady_dpcm'>;
export const FF_DECODER_WBMP = 'wbmp' as FFVideoDecoder<'wbmp'>;
export const FF_DECODER_WCMV = 'wcmv' as FFVideoDecoder<'wcmv'>;
export const FF_DECODER_WEBP = 'webp' as FFVideoDecoder<'webp'>;
export const FF_DECODER_WEBP_ANIM = 'webp_anim' as FFVideoDecoder<'webp_anim'>;
export const FF_DECODER_WMV1 = 'wmv1' as FFVideoDecoder<'wmv1'>;
export const FF_DECODER_WMV2 = 'wmv2' as FFVideoDecoder<'wmv2'>;
export const FF_DECODER_WMV3 = 'wmv3' as FFVideoDecoder<'wmv3'>;
export const FF_DECODER_WMV3IMAGE = 'wmv3image' as FFVideoDecoder<'wmv3image'>;
export const FF_DECODER_WNV1 = 'wnv1' as FFVideoDecoder<'wnv1'>;
export const FF_DECODER_WRAPPED_AVFRAME = 'wrapped_avframe' as FFVideoDecoder<'wrapped_avframe'>;
export const FF_DECODER_WS_SND1 = 'ws_snd1' as FFVideoDecoder<'ws_snd1'>;
export const FF_DECODER_XAN_DPCM = 'xan_dpcm' as FFVideoDecoder<'xan_dpcm'>;
export const FF_DECODER_XAN_WC3 = 'xan_wc3' as FFVideoDecoder<'xan_wc3'>;
export const FF_DECODER_XAN_WC4 = 'xan_wc4' as FFVideoDecoder<'xan_wc4'>;
export const FF_DECODER_XBIN = 'xbin' as FFVideoDecoder<'xbin'>;
export const FF_DECODER_XBM = 'xbm' as FFVideoDecoder<'xbm'>;
export const FF_DECODER_XFACE = 'xface' as FFVideoDecoder<'xface'>;
export const FF_DECODER_XL = 'xl' as FFVideoDecoder<'xl'>;
export const FF_DECODER_XPM = 'xpm' as FFVideoDecoder<'xpm'>;
export const FF_DECODER_XWD = 'xwd' as FFVideoDecoder<'xwd'>;
export const FF_DECODER_Y41P = 'y41p' as FFVideoDecoder<'y41p'>;
export const FF_DECODER_YLC = 'ylc' as FFVideoDecoder<'ylc'>;
export const FF_DECODER_YOP = 'yop' as FFVideoDecoder<'yop'>;
export const FF_DECODER_YUV4 = 'yuv4' as FFVideoDecoder<'yuv4'>;
export const FF_DECODER_ZERO12V = '012v' as FFVideoDecoder<'012v'>;
export const FF_DECODER_ZEROCODEC = 'zerocodec' as FFVideoDecoder<'zerocodec'>;
export const FF_DECODER_ZLIB = 'zlib' as FFVideoDecoder<'zlib'>;
export const FF_DECODER_ZMBV = 'zmbv' as FFVideoDecoder<'zmbv'>;

// Hardware video decoders

// NVIDIA CUVID
export const FF_DECODER_AV1_CUVID = 'av1_cuvid' as FFVideoDecoder<'av1_cuvid'>;
export const FF_DECODER_H264_CUVID = 'h264_cuvid' as FFVideoDecoder<'h264_cuvid'>;
export const FF_DECODER_HEVC_CUVID = 'hevc_cuvid' as FFVideoDecoder<'hevc_cuvid'>;
export const FF_DECODER_MJPEG_CUVID = 'mjpeg_cuvid' as FFVideoDecoder<'mjpeg_cuvid'>;
export const FF_DECODER_MPEG1_CUVID = 'mpeg1_cuvid' as FFVideoDecoder<'mpeg1_cuvid'>;
export const FF_DECODER_MPEG2_CUVID = 'mpeg2_cuvid' as FFVideoDecoder<'mpeg2_cuvid'>;
export const FF_DECODER_MPEG4_CUVID = 'mpeg4_cuvid' as FFVideoDecoder<'mpeg4_cuvid'>;
export const FF_DECODER_VC1_CUVID = 'vc1_cuvid' as FFVideoDecoder<'vc1_cuvid'>;
export const FF_DECODER_VP8_CUVID = 'vp8_cuvid' as FFVideoDecoder<'vp8_cuvid'>;
export const FF_DECODER_VP9_CUVID = 'vp9_cuvid' as FFVideoDecoder<'vp9_cuvid'>;

// Android MediaCodec
export const FF_DECODER_AV1_MEDIACODEC = 'av1_mediacodec' as FFVideoDecoder<'av1_mediacodec'>;
export const FF_DECODER_H264_MEDIACODEC = 'h264_mediacodec' as FFVideoDecoder<'h264_mediacodec'>;
export const FF_DECODER_HEVC_MEDIACODEC = 'hevc_mediacodec' as FFVideoDecoder<'hevc_mediacodec'>;
export const FF_DECODER_MPEG2_MEDIACODEC = 'mpeg2_mediacodec' as FFVideoDecoder<'mpeg2_mediacodec'>;
export const FF_DECODER_MPEG4_MEDIACODEC = 'mpeg4_mediacodec' as FFVideoDecoder<'mpeg4_mediacodec'>;
export const FF_DECODER_VP8_MEDIACODEC = 'vp8_mediacodec' as FFVideoDecoder<'vp8_mediacodec'>;
export const FF_DECODER_VP9_MEDIACODEC = 'vp9_mediacodec' as FFVideoDecoder<'vp9_mediacodec'>;

// Intel Quick Sync
export const FF_DECODER_AV1_QSV = 'av1_qsv' as FFVideoDecoder<'av1_qsv'>;
export const FF_DECODER_H264_QSV = 'h264_qsv' as FFVideoDecoder<'h264_qsv'>;
export const FF_DECODER_HEVC_QSV = 'hevc_qsv' as FFVideoDecoder<'hevc_qsv'>;
export const FF_DECODER_MJPEG_QSV = 'mjpeg_qsv' as FFVideoDecoder<'mjpeg_qsv'>;
export const FF_DECODER_MPEG2_QSV = 'mpeg2_qsv' as FFVideoDecoder<'mpeg2_qsv'>;
export const FF_DECODER_VC1_QSV = 'vc1_qsv' as FFVideoDecoder<'vc1_qsv'>;
export const FF_DECODER_VP8_QSV = 'vp8_qsv' as FFVideoDecoder<'vp8_qsv'>;
export const FF_DECODER_VP9_QSV = 'vp9_qsv' as FFVideoDecoder<'vp9_qsv'>;
export const FF_DECODER_VVC_QSV = 'vvc_qsv' as FFVideoDecoder<'vvc_qsv'>;

// Rockchip MPP
export const FF_DECODER_AV1_RKMPP = 'av1_rkmpp' as FFVideoDecoder<'av1_rkmpp'>;
export const FF_DECODER_H263_RKMPP = 'h263_rkmpp' as FFVideoDecoder<'h263_rkmpp'>;
export const FF_DECODER_H264_RKMPP = 'h264_rkmpp' as FFVideoDecoder<'h264_rkmpp'>;
export const FF_DECODER_HEVC_RKMPP = 'hevc_rkmpp' as FFVideoDecoder<'hevc_rkmpp'>;
export const FF_DECODER_MJPEG_RKMPP = 'mjpeg_rkmpp' as FFVideoDecoder<'mjpeg_rkmpp'>;
export const FF_DECODER_MPEG1_RKMPP = 'mpeg1_rkmpp' as FFVideoDecoder<'mpeg1_rkmpp'>;
export const FF_DECODER_MPEG2_RKMPP = 'mpeg2_rkmpp' as FFVideoDecoder<'mpeg2_rkmpp'>;
export const FF_DECODER_MPEG4_RKMPP = 'mpeg4_rkmpp' as FFVideoDecoder<'mpeg4_rkmpp'>;
export const FF_DECODER_VP8_RKMPP = 'vp8_rkmpp' as FFVideoDecoder<'vp8_rkmpp'>;
export const FF_DECODER_VP9_RKMPP = 'vp9_rkmpp' as FFVideoDecoder<'vp9_rkmpp'>;

// V4L2 M2M
export const FF_DECODER_H263_V4L2M2M = 'h263_v4l2m2m' as FFVideoDecoder<'h263_v4l2m2m'>;
export const FF_DECODER_H264_V4L2M2M = 'h264_v4l2m2m' as FFVideoDecoder<'h264_v4l2m2m'>;
export const FF_DECODER_HEVC_V4L2M2M = 'hevc_v4l2m2m' as FFVideoDecoder<'hevc_v4l2m2m'>;
export const FF_DECODER_MPEG1_V4L2M2M = 'mpeg1_v4l2m2m' as FFVideoDecoder<'mpeg1_v4l2m2m'>;
export const FF_DECODER_MPEG2_V4L2M2M = 'mpeg2_v4l2m2m' as FFVideoDecoder<'mpeg2_v4l2m2m'>;
export const FF_DECODER_MPEG4_V4L2M2M = 'mpeg4_v4l2m2m' as FFVideoDecoder<'mpeg4_v4l2m2m'>;
export const FF_DECODER_VC1_V4L2M2M = 'vc1_v4l2m2m' as FFVideoDecoder<'vc1_v4l2m2m'>;
export const FF_DECODER_VP8_V4L2M2M = 'vp8_v4l2m2m' as FFVideoDecoder<'vp8_v4l2m2m'>;
export const FF_DECODER_VP9_V4L2M2M = 'vp9_v4l2m2m' as FFVideoDecoder<'vp9_v4l2m2m'>;

// Raspberry Pi MMAL
export const FF_DECODER_H264_MMAL = 'h264_mmal' as FFVideoDecoder<'h264_mmal'>;
export const FF_DECODER_MPEG2_MMAL = 'mpeg2_mmal' as FFVideoDecoder<'mpeg2_mmal'>;
export const FF_DECODER_MPEG4_MMAL = 'mpeg4_mmal' as FFVideoDecoder<'mpeg4_mmal'>;
export const FF_DECODER_VC1_MMAL = 'vc1_mmal' as FFVideoDecoder<'vc1_mmal'>;

// ============================================================================
// AUDIO DECODERS (174 software, 19 hardware)
// ============================================================================

// Software audio decoders
export const FF_DECODER_AAC = 'aac' as FFAudioDecoder<'aac'>;
export const FF_DECODER_AAC_FIXED = 'aac_fixed' as FFAudioDecoder<'aac_fixed'>;
export const FF_DECODER_AAC_LATM = 'aac_latm' as FFAudioDecoder<'aac_latm'>;
export const FF_DECODER_AC3 = 'ac3' as FFAudioDecoder<'ac3'>;
export const FF_DECODER_AC3_FIXED = 'ac3_fixed' as FFAudioDecoder<'ac3_fixed'>;
export const FF_DECODER_AC4 = 'ac4' as FFAudioDecoder<'ac4'>;
export const FF_DECODER_ADPCM_4XM = 'adpcm_4xm' as FFAudioDecoder<'adpcm_4xm'>;
export const FF_DECODER_ADPCM_ADX = 'adpcm_adx' as FFAudioDecoder<'adpcm_adx'>;
export const FF_DECODER_ADPCM_AFC = 'adpcm_afc' as FFAudioDecoder<'adpcm_afc'>;
export const FF_DECODER_ADPCM_AGM = 'adpcm_agm' as FFAudioDecoder<'adpcm_agm'>;
export const FF_DECODER_ADPCM_AICA = 'adpcm_aica' as FFAudioDecoder<'adpcm_aica'>;
export const FF_DECODER_ADPCM_ARGO = 'adpcm_argo' as FFAudioDecoder<'adpcm_argo'>;
export const FF_DECODER_ADPCM_CIRCUS = 'adpcm_circus' as FFAudioDecoder<'adpcm_circus'>;
export const FF_DECODER_ADPCM_CT = 'adpcm_ct' as FFAudioDecoder<'adpcm_ct'>;
export const FF_DECODER_ADPCM_DTK = 'adpcm_dtk' as FFAudioDecoder<'adpcm_dtk'>;
export const FF_DECODER_ADPCM_EA = 'adpcm_ea' as FFAudioDecoder<'adpcm_ea'>;
export const FF_DECODER_ADPCM_EA_MAXIS_XA = 'adpcm_ea_maxis_xa' as FFAudioDecoder<'adpcm_ea_maxis_xa'>;
export const FF_DECODER_ADPCM_EA_R1 = 'adpcm_ea_r1' as FFAudioDecoder<'adpcm_ea_r1'>;
export const FF_DECODER_ADPCM_EA_R2 = 'adpcm_ea_r2' as FFAudioDecoder<'adpcm_ea_r2'>;
export const FF_DECODER_ADPCM_EA_R3 = 'adpcm_ea_r3' as FFAudioDecoder<'adpcm_ea_r3'>;
export const FF_DECODER_ADPCM_EA_XAS = 'adpcm_ea_xas' as FFAudioDecoder<'adpcm_ea_xas'>;
export const FF_DECODER_ADPCM_G722 = 'g722' as FFAudioDecoder<'g722'>;
export const FF_DECODER_ADPCM_G726 = 'g726' as FFAudioDecoder<'g726'>;
export const FF_DECODER_ADPCM_G726LE = 'g726le' as FFAudioDecoder<'g726le'>;
export const FF_DECODER_ADPCM_IMA_ACORN = 'adpcm_ima_acorn' as FFAudioDecoder<'adpcm_ima_acorn'>;
export const FF_DECODER_ADPCM_IMA_ALP = 'adpcm_ima_alp' as FFAudioDecoder<'adpcm_ima_alp'>;
export const FF_DECODER_ADPCM_IMA_AMV = 'adpcm_ima_amv' as FFAudioDecoder<'adpcm_ima_amv'>;
export const FF_DECODER_ADPCM_IMA_APC = 'adpcm_ima_apc' as FFAudioDecoder<'adpcm_ima_apc'>;
export const FF_DECODER_ADPCM_IMA_APM = 'adpcm_ima_apm' as FFAudioDecoder<'adpcm_ima_apm'>;
export const FF_DECODER_ADPCM_IMA_CUNNING = 'adpcm_ima_cunning' as FFAudioDecoder<'adpcm_ima_cunning'>;
export const FF_DECODER_ADPCM_IMA_DAT4 = 'adpcm_ima_dat4' as FFAudioDecoder<'adpcm_ima_dat4'>;
export const FF_DECODER_ADPCM_IMA_DK3 = 'adpcm_ima_dk3' as FFAudioDecoder<'adpcm_ima_dk3'>;
export const FF_DECODER_ADPCM_IMA_DK4 = 'adpcm_ima_dk4' as FFAudioDecoder<'adpcm_ima_dk4'>;
export const FF_DECODER_ADPCM_IMA_EA_EACS = 'adpcm_ima_ea_eacs' as FFAudioDecoder<'adpcm_ima_ea_eacs'>;
export const FF_DECODER_ADPCM_IMA_EA_SEAD = 'adpcm_ima_ea_sead' as FFAudioDecoder<'adpcm_ima_ea_sead'>;
export const FF_DECODER_ADPCM_IMA_ESCAPE = 'adpcm_ima_escape' as FFAudioDecoder<'adpcm_ima_escape'>;
export const FF_DECODER_ADPCM_IMA_HVQM2 = 'adpcm_ima_hvqm2' as FFAudioDecoder<'adpcm_ima_hvqm2'>;
export const FF_DECODER_ADPCM_IMA_HVQM4 = 'adpcm_ima_hvqm4' as FFAudioDecoder<'adpcm_ima_hvqm4'>;
export const FF_DECODER_ADPCM_IMA_ISS = 'adpcm_ima_iss' as FFAudioDecoder<'adpcm_ima_iss'>;
export const FF_DECODER_ADPCM_IMA_MAGIX = 'adpcm_ima_magix' as FFAudioDecoder<'adpcm_ima_magix'>;
export const FF_DECODER_ADPCM_IMA_MOFLEX = 'adpcm_ima_moflex' as FFAudioDecoder<'adpcm_ima_moflex'>;
export const FF_DECODER_ADPCM_IMA_MTF = 'adpcm_ima_mtf' as FFAudioDecoder<'adpcm_ima_mtf'>;
export const FF_DECODER_ADPCM_IMA_OKI = 'adpcm_ima_oki' as FFAudioDecoder<'adpcm_ima_oki'>;
export const FF_DECODER_ADPCM_IMA_PDA = 'adpcm_ima_pda' as FFAudioDecoder<'adpcm_ima_pda'>;
export const FF_DECODER_ADPCM_IMA_QT = 'adpcm_ima_qt' as FFAudioDecoder<'adpcm_ima_qt'>;
export const FF_DECODER_ADPCM_IMA_RAD = 'adpcm_ima_rad' as FFAudioDecoder<'adpcm_ima_rad'>;
export const FF_DECODER_ADPCM_IMA_SMJPEG = 'adpcm_ima_smjpeg' as FFAudioDecoder<'adpcm_ima_smjpeg'>;
export const FF_DECODER_ADPCM_IMA_SSI = 'adpcm_ima_ssi' as FFAudioDecoder<'adpcm_ima_ssi'>;
export const FF_DECODER_ADPCM_IMA_WAV = 'adpcm_ima_wav' as FFAudioDecoder<'adpcm_ima_wav'>;
export const FF_DECODER_ADPCM_IMA_WS = 'adpcm_ima_ws' as FFAudioDecoder<'adpcm_ima_ws'>;
export const FF_DECODER_ADPCM_IMA_XBOX = 'adpcm_ima_xbox' as FFAudioDecoder<'adpcm_ima_xbox'>;
export const FF_DECODER_ADPCM_MS = 'adpcm_ms' as FFAudioDecoder<'adpcm_ms'>;
export const FF_DECODER_ADPCM_MTAF = 'adpcm_mtaf' as FFAudioDecoder<'adpcm_mtaf'>;
export const FF_DECODER_ADPCM_N64 = 'adpcm_n64' as FFAudioDecoder<'adpcm_n64'>;
export const FF_DECODER_ADPCM_PSX = 'adpcm_psx' as FFAudioDecoder<'adpcm_psx'>;
export const FF_DECODER_ADPCM_PSXC = 'adpcm_psxc' as FFAudioDecoder<'adpcm_psxc'>;
export const FF_DECODER_ADPCM_SANYO = 'adpcm_sanyo' as FFAudioDecoder<'adpcm_sanyo'>;
export const FF_DECODER_ADPCM_SBPRO_2 = 'adpcm_sbpro_2' as FFAudioDecoder<'adpcm_sbpro_2'>;
export const FF_DECODER_ADPCM_SBPRO_3 = 'adpcm_sbpro_3' as FFAudioDecoder<'adpcm_sbpro_3'>;
export const FF_DECODER_ADPCM_SBPRO_4 = 'adpcm_sbpro_4' as FFAudioDecoder<'adpcm_sbpro_4'>;
export const FF_DECODER_ADPCM_SWF = 'adpcm_swf' as FFAudioDecoder<'adpcm_swf'>;
export const FF_DECODER_ADPCM_THP = 'adpcm_thp' as FFAudioDecoder<'adpcm_thp'>;
export const FF_DECODER_ADPCM_THP_LE = 'adpcm_thp_le' as FFAudioDecoder<'adpcm_thp_le'>;
export const FF_DECODER_ADPCM_VIMA = 'adpcm_vima' as FFAudioDecoder<'adpcm_vima'>;
export const FF_DECODER_ADPCM_XA = 'adpcm_xa' as FFAudioDecoder<'adpcm_xa'>;
export const FF_DECODER_ADPCM_XMD = 'adpcm_xmd' as FFAudioDecoder<'adpcm_xmd'>;
export const FF_DECODER_ADPCM_YAMAHA = 'adpcm_yamaha' as FFAudioDecoder<'adpcm_yamaha'>;
export const FF_DECODER_ADPCM_ZORK = 'adpcm_zork' as FFAudioDecoder<'adpcm_zork'>;
export const FF_DECODER_ALAC = 'alac' as FFAudioDecoder<'alac'>;
export const FF_DECODER_AMRNB = 'amrnb' as FFAudioDecoder<'amrnb'>;
export const FF_DECODER_AMRWB = 'amrwb' as FFAudioDecoder<'amrwb'>;
export const FF_DECODER_APTX = 'aptx' as FFAudioDecoder<'aptx'>;
export const FF_DECODER_APTX_HD = 'aptx_hd' as FFAudioDecoder<'aptx_hd'>;
export const FF_DECODER_ATRAC1 = 'atrac1' as FFAudioDecoder<'atrac1'>;
export const FF_DECODER_ATRAC3 = 'atrac3' as FFAudioDecoder<'atrac3'>;
export const FF_DECODER_ATRAC3AL = 'atrac3al' as FFAudioDecoder<'atrac3al'>;
export const FF_DECODER_ATRAC3P = 'atrac3plus' as FFAudioDecoder<'atrac3plus'>;
export const FF_DECODER_ATRAC3PAL = 'atrac3plusal' as FFAudioDecoder<'atrac3plusal'>;
export const FF_DECODER_ATRAC9 = 'atrac9' as FFAudioDecoder<'atrac9'>;
export const FF_DECODER_COMFORTNOISE = 'comfortnoise' as FFAudioDecoder<'comfortnoise'>;
export const FF_DECODER_COOK = 'cook' as FFAudioDecoder<'cook'>;
export const FF_DECODER_DCA = 'dca' as FFAudioDecoder<'dca'>;
export const FF_DECODER_DFPWM = 'dfpwm' as FFAudioDecoder<'dfpwm'>;
export const FF_DECODER_DOLBY_E = 'dolby_e' as FFAudioDecoder<'dolby_e'>;
export const FF_DECODER_EAC3 = 'eac3' as FFAudioDecoder<'eac3'>;
export const FF_DECODER_FLAC = 'flac' as FFAudioDecoder<'flac'>;
export const FF_DECODER_G723_1 = 'g723_1' as FFAudioDecoder<'g723_1'>;
export const FF_DECODER_G728 = 'g728' as FFAudioDecoder<'g728'>;
export const FF_DECODER_G729 = 'g729' as FFAudioDecoder<'g729'>;
export const FF_DECODER_GSM = 'gsm' as FFAudioDecoder<'gsm'>;
export const FF_DECODER_GSM_MS = 'gsm_ms' as FFAudioDecoder<'gsm_ms'>;
export const FF_DECODER_ILBC = 'ilbc' as FFAudioDecoder<'ilbc'>;
export const FF_DECODER_IMC = 'imc' as FFAudioDecoder<'imc'>;
export const FF_DECODER_LIBFDK_AAC = 'libfdk_aac' as FFAudioDecoder<'libfdk_aac'>;
export const FF_DECODER_LIBOPUS = 'libopus' as FFAudioDecoder<'libopus'>;
export const FF_DECODER_LIBSPEEX = 'libspeex' as FFAudioDecoder<'libspeex'>;
export const FF_DECODER_LIBVORBIS = 'libvorbis' as FFAudioDecoder<'libvorbis'>;
export const FF_DECODER_MACE3 = 'mace3' as FFAudioDecoder<'mace3'>;
export const FF_DECODER_MACE6 = 'mace6' as FFAudioDecoder<'mace6'>;
export const FF_DECODER_METASOUND = 'metasound' as FFAudioDecoder<'metasound'>;
export const FF_DECODER_MLP = 'mlp' as FFAudioDecoder<'mlp'>;
export const FF_DECODER_MP1 = 'mp1' as FFAudioDecoder<'mp1'>;
export const FF_DECODER_MP1FLOAT = 'mp1float' as FFAudioDecoder<'mp1float'>;
export const FF_DECODER_MP2 = 'mp2' as FFAudioDecoder<'mp2'>;
export const FF_DECODER_MP2FLOAT = 'mp2float' as FFAudioDecoder<'mp2float'>;
export const FF_DECODER_MP3 = 'mp3' as FFAudioDecoder<'mp3'>;
export const FF_DECODER_MP3ADU = 'mp3adu' as FFAudioDecoder<'mp3adu'>;
export const FF_DECODER_MP3ADUFLOAT = 'mp3adufloat' as FFAudioDecoder<'mp3adufloat'>;
export const FF_DECODER_MP3FLOAT = 'mp3float' as FFAudioDecoder<'mp3float'>;
export const FF_DECODER_MP3ON4 = 'mp3on4' as FFAudioDecoder<'mp3on4'>;
export const FF_DECODER_MP3ON4FLOAT = 'mp3on4float' as FFAudioDecoder<'mp3on4float'>;
export const FF_DECODER_NELLYMOSER = 'nellymoser' as FFAudioDecoder<'nellymoser'>;
export const FF_DECODER_ON2AVC = 'on2avc' as FFAudioDecoder<'on2avc'>;
export const FF_DECODER_OPUS = 'opus' as FFAudioDecoder<'opus'>;
export const FF_DECODER_PCM_ALAW = 'pcm_alaw' as FFAudioDecoder<'pcm_alaw'>;
export const FF_DECODER_PCM_BLURAY = 'pcm_bluray' as FFAudioDecoder<'pcm_bluray'>;
export const FF_DECODER_PCM_DVD = 'pcm_dvd' as FFAudioDecoder<'pcm_dvd'>;
export const FF_DECODER_PCM_F16LE = 'pcm_f16le' as FFAudioDecoder<'pcm_f16le'>;
export const FF_DECODER_PCM_F24LE = 'pcm_f24le' as FFAudioDecoder<'pcm_f24le'>;
export const FF_DECODER_PCM_F32BE = 'pcm_f32be' as FFAudioDecoder<'pcm_f32be'>;
export const FF_DECODER_PCM_F32LE = 'pcm_f32le' as FFAudioDecoder<'pcm_f32le'>;
export const FF_DECODER_PCM_F64BE = 'pcm_f64be' as FFAudioDecoder<'pcm_f64be'>;
export const FF_DECODER_PCM_F64LE = 'pcm_f64le' as FFAudioDecoder<'pcm_f64le'>;
export const FF_DECODER_PCM_LXF = 'pcm_lxf' as FFAudioDecoder<'pcm_lxf'>;
export const FF_DECODER_PCM_MULAW = 'pcm_mulaw' as FFAudioDecoder<'pcm_mulaw'>;
export const FF_DECODER_PCM_S16BE = 'pcm_s16be' as FFAudioDecoder<'pcm_s16be'>;
export const FF_DECODER_PCM_S16BE_PLANAR = 'pcm_s16be_planar' as FFAudioDecoder<'pcm_s16be_planar'>;
export const FF_DECODER_PCM_S16LE = 'pcm_s16le' as FFAudioDecoder<'pcm_s16le'>;
export const FF_DECODER_PCM_S16LE_PLANAR = 'pcm_s16le_planar' as FFAudioDecoder<'pcm_s16le_planar'>;
export const FF_DECODER_PCM_S24BE = 'pcm_s24be' as FFAudioDecoder<'pcm_s24be'>;
export const FF_DECODER_PCM_S24DAUD = 'pcm_s24daud' as FFAudioDecoder<'pcm_s24daud'>;
export const FF_DECODER_PCM_S24LE = 'pcm_s24le' as FFAudioDecoder<'pcm_s24le'>;
export const FF_DECODER_PCM_S24LE_PLANAR = 'pcm_s24le_planar' as FFAudioDecoder<'pcm_s24le_planar'>;
export const FF_DECODER_PCM_S32BE = 'pcm_s32be' as FFAudioDecoder<'pcm_s32be'>;
export const FF_DECODER_PCM_S32LE = 'pcm_s32le' as FFAudioDecoder<'pcm_s32le'>;
export const FF_DECODER_PCM_S32LE_PLANAR = 'pcm_s32le_planar' as FFAudioDecoder<'pcm_s32le_planar'>;
export const FF_DECODER_PCM_S64BE = 'pcm_s64be' as FFAudioDecoder<'pcm_s64be'>;
export const FF_DECODER_PCM_S64LE = 'pcm_s64le' as FFAudioDecoder<'pcm_s64le'>;
export const FF_DECODER_PCM_S8 = 'pcm_s8' as FFAudioDecoder<'pcm_s8'>;
export const FF_DECODER_PCM_S8_PLANAR = 'pcm_s8_planar' as FFAudioDecoder<'pcm_s8_planar'>;
export const FF_DECODER_PCM_SGA = 'pcm_sga' as FFAudioDecoder<'pcm_sga'>;
export const FF_DECODER_PCM_U16BE = 'pcm_u16be' as FFAudioDecoder<'pcm_u16be'>;
export const FF_DECODER_PCM_U16LE = 'pcm_u16le' as FFAudioDecoder<'pcm_u16le'>;
export const FF_DECODER_PCM_U24BE = 'pcm_u24be' as FFAudioDecoder<'pcm_u24be'>;
export const FF_DECODER_PCM_U24LE = 'pcm_u24le' as FFAudioDecoder<'pcm_u24le'>;
export const FF_DECODER_PCM_U32BE = 'pcm_u32be' as FFAudioDecoder<'pcm_u32be'>;
export const FF_DECODER_PCM_U32LE = 'pcm_u32le' as FFAudioDecoder<'pcm_u32le'>;
export const FF_DECODER_PCM_U8 = 'pcm_u8' as FFAudioDecoder<'pcm_u8'>;
export const FF_DECODER_PCM_VIDC = 'pcm_vidc' as FFAudioDecoder<'pcm_vidc'>;
export const FF_DECODER_QCELP = 'qcelp' as FFAudioDecoder<'qcelp'>;
export const FF_DECODER_QDM2 = 'qdm2' as FFAudioDecoder<'qdm2'>;
export const FF_DECODER_QDMC = 'qdmc' as FFAudioDecoder<'qdmc'>;
export const FF_DECODER_RALF = 'ralf' as FFAudioDecoder<'ralf'>;
export const FF_DECODER_REALTEXT = 'realtext' as FFAudioDecoder<'realtext'>;
export const FF_DECODER_S302M = 's302m' as FFAudioDecoder<'s302m'>;
export const FF_DECODER_SBC = 'sbc' as FFAudioDecoder<'sbc'>;
export const FF_DECODER_SIPR = 'sipr' as FFAudioDecoder<'sipr'>;
export const FF_DECODER_SONIC = 'sonic' as FFAudioDecoder<'sonic'>;
export const FF_DECODER_TAK = 'tak' as FFAudioDecoder<'tak'>;
export const FF_DECODER_TRUEHD = 'truehd' as FFAudioDecoder<'truehd'>;
export const FF_DECODER_TRUESPEECH = 'truespeech' as FFAudioDecoder<'truespeech'>;
export const FF_DECODER_TTA = 'tta' as FFAudioDecoder<'tta'>;
export const FF_DECODER_TWINVQ = 'twinvq' as FFAudioDecoder<'twinvq'>;
export const FF_DECODER_VMDAUDIO = 'vmdaudio' as FFAudioDecoder<'vmdaudio'>;
export const FF_DECODER_VORBIS = 'vorbis' as FFAudioDecoder<'vorbis'>;
export const FF_DECODER_WAVARC = 'wavarc' as FFAudioDecoder<'wavarc'>;
export const FF_DECODER_WAVPACK = 'wavpack' as FFAudioDecoder<'wavpack'>;
export const FF_DECODER_WMALOSSLESS = 'wmalossless' as FFAudioDecoder<'wmalossless'>;
export const FF_DECODER_WMAPRO = 'wmapro' as FFAudioDecoder<'wmapro'>;
export const FF_DECODER_WMAV1 = 'wmav1' as FFAudioDecoder<'wmav1'>;
export const FF_DECODER_WMAV2 = 'wmav2' as FFAudioDecoder<'wmav2'>;
export const FF_DECODER_WMAVOICE = 'wmavoice' as FFAudioDecoder<'wmavoice'>;
export const FF_DECODER_XMA1 = 'xma1' as FFAudioDecoder<'xma1'>;
export const FF_DECODER_XMA2 = 'xma2' as FFAudioDecoder<'xma2'>;

// Hardware audio decoders
export const FF_DECODER_AAC_AT = 'aac_at' as FFAudioDecoder<'aac_at'>;
export const FF_DECODER_AAC_MEDIACODEC = 'aac_mediacodec' as FFAudioDecoder<'aac_mediacodec'>;
export const FF_DECODER_AC3_AT = 'ac3_at' as FFAudioDecoder<'ac3_at'>;
export const FF_DECODER_ADPCM_IMA_QT_AT = 'adpcm_ima_qt_at' as FFAudioDecoder<'adpcm_ima_qt_at'>;
export const FF_DECODER_ALAC_AT = 'alac_at' as FFAudioDecoder<'alac_at'>;
export const FF_DECODER_AMR_NB_AT = 'amr_nb_at' as FFAudioDecoder<'amr_nb_at'>;
export const FF_DECODER_AMRNB_MEDIACODEC = 'amrnb_mediacodec' as FFAudioDecoder<'amrnb_mediacodec'>;
export const FF_DECODER_AMRWB_MEDIACODEC = 'amrwb_mediacodec' as FFAudioDecoder<'amrwb_mediacodec'>;
export const FF_DECODER_EAC3_AT = 'eac3_at' as FFAudioDecoder<'eac3_at'>;
export const FF_DECODER_GSM_MS_AT = 'gsm_ms_at' as FFAudioDecoder<'gsm_ms_at'>;
export const FF_DECODER_ILBC_AT = 'ilbc_at' as FFAudioDecoder<'ilbc_at'>;
export const FF_DECODER_MP1_AT = 'mp1_at' as FFAudioDecoder<'mp1_at'>;
export const FF_DECODER_MP2_AT = 'mp2_at' as FFAudioDecoder<'mp2_at'>;
export const FF_DECODER_MP3_AT = 'mp3_at' as FFAudioDecoder<'mp3_at'>;
export const FF_DECODER_MP3_MEDIACODEC = 'mp3_mediacodec' as FFAudioDecoder<'mp3_mediacodec'>;
export const FF_DECODER_PCM_ALAW_AT = 'pcm_alaw_at' as FFAudioDecoder<'pcm_alaw_at'>;
export const FF_DECODER_PCM_MULAW_AT = 'pcm_mulaw_at' as FFAudioDecoder<'pcm_mulaw_at'>;
export const FF_DECODER_QDM2_AT = 'qdm2_at' as FFAudioDecoder<'qdm2_at'>;
export const FF_DECODER_QDMC_AT = 'qdmc_at' as FFAudioDecoder<'qdmc_at'>;

// ============================================================================
// SUBTITLE DECODERS (18 decoders)
// ============================================================================

export const FF_DECODER_ASS = 'ass' as FFSubtitleDecoder<'ass'>;
export const FF_DECODER_DVBSUB = 'dvbsub' as FFSubtitleDecoder<'dvbsub'>;
export const FF_DECODER_DVDSUB = 'dvdsub' as FFSubtitleDecoder<'dvdsub'>;
export const FF_DECODER_JACOSUB = 'jacosub' as FFSubtitleDecoder<'jacosub'>;
export const FF_DECODER_MICRODVD = 'microdvd' as FFSubtitleDecoder<'microdvd'>;
export const FF_DECODER_MPL2 = 'mpl2' as FFSubtitleDecoder<'mpl2'>;
export const FF_DECODER_PJS = 'pjs' as FFSubtitleDecoder<'pjs'>;
export const FF_DECODER_SAMI = 'sami' as FFSubtitleDecoder<'sami'>;
export const FF_DECODER_SRT = 'srt' as FFSubtitleDecoder<'srt'>;
export const FF_DECODER_SSA = 'ssa' as FFSubtitleDecoder<'ssa'>;
export const FF_DECODER_STL = 'stl' as FFSubtitleDecoder<'stl'>;
export const FF_DECODER_SUBRIP = 'subrip' as FFSubtitleDecoder<'subrip'>;
export const FF_DECODER_SUBVIEWER = 'subviewer' as FFSubtitleDecoder<'subviewer'>;
export const FF_DECODER_SUBVIEWER1 = 'subviewer1' as FFSubtitleDecoder<'subviewer1'>;
export const FF_DECODER_TEXT = 'text' as FFSubtitleDecoder<'text'>;
export const FF_DECODER_VPLAYER = 'vplayer' as FFSubtitleDecoder<'vplayer'>;
export const FF_DECODER_WEBVTT = 'webvtt' as FFSubtitleDecoder<'webvtt'>;
export const FF_DECODER_XSUB = 'xsub' as FFSubtitleDecoder<'xsub'>;
